
[package]
name = "checkers"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
slint = "1.14"
rdev = "0.5.3"

[build-dependencies]
slint-build = "1.14"

[features]
ui = []
default = ["ui"]
